"use client";
import React, { useState } from "react";
import { authenticateCeramic } from "@/utils/auth";
import { useCeramicContext } from "@/context";

const AuthPrompt = () => {
  const [isVisible, setIsVisible] = useState(true);
  const clients = useCeramicContext();
  const { ceramic, composeClient } = clients;
  const isLogged = () => {
    return localStorage.getItem("logged_in") == "true";
  };

  const handleOpen = () => {
    if (localStorage.getItem("logged_in")) {
      setIsVisible(true);
    } else {
      setIsVisible(false);
    }
  };

  const handleKeyDid = () => {
    localStorage.setItem("ceramic:auth_type", "key");
    authenticateCeramic(ceramic, composeClient);
    setIsVisible(false);
  };

  const handleEthPkh = () => {
    localStorage.setItem("ceramic:auth_type", "eth");
    authenticateCeramic(ceramic, composeClient);
    setIsVisible(false);
  };

  return (
    <div>
      {isVisible && (
        <div className="relative p-4 w-full max-w-md max-h-full">
          <div className="relative p-6 bg-white rounded-lg shadow dark:bg-gray-700 flex flex-col">
            <div className="flex flex-col items-center">
              <h2 className="text-xl">Authenticate</h2>
              <div className="flex flex-row gap-3 mb-3">
                <button
                  className="text-white bg-blue-600 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-bue-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center"
                  onClick={handleKeyDid}
                >
                  Key DID
                </button>
                <button
                  className="text-white bg-indigo-600 hover:bg-indigo-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-bue-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center"
                  onClick={handleEthPkh}
                >
                  Ethereum DID PKH
                </button>
              </div>
            </div>
            <div className="text-sm text-muted">
              <strong>Key DID:</strong> A DID generated by Ceramic that is
              stored in your browser&apos;s local storage. It should already be
              generated during setup process.
              <br />
              <strong>Ethereum DID PKH:</strong> A DID generated by your wallet
              (in simpler terms: login with MetaMask).
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AuthPrompt;
